name: Create synapse environment
description: Create a new Synapse environment in the configured Azure Account
title: "[Create]: "
labels: ["resource creation"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the needed info and the resources will be automatically created for you!
  - type: input
    id: resource-name
    attributes:
      label: Resource name
      description: How should the Synapse be named
      placeholder: ex. mysynapse
    validations:
      required: true
  - type: checkboxes
    id: demo-data
    attributes:
      label: Demo data deploy
      description: Check this box if you want some demo data deployed into your environment
      options:
        - label: Demo data
          required: true
