name: Create synapse environment
description: Create a new Synapse environment in the configured Azure Account
title: "[Create]: "
labels: ["resource creation"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill the needed info and the resources will be automatically created for you!
  - type: input
    id: resource-name
    attributes:
      label: Resource name
      description: How should the Synapse be named
      placeholder: ex. mysynapse
    validations:
      required: true
  - type: dropdown
    id: demo-data
    attributes:
      label: Demo data deploy
      description: Choose what kind of environment you want deployed to your resource group
      options:
        - Demo data
        - Clean
      validations:
          required: true
