# This is a basic workflow to help you get started with Actions

name: Create Infra

on:
  issues:
    types: [ opened ]

jobs:      
  deploy:
    if: startsWith(github.event.issue.title, '[Cre]') != 'true'
    needs: check
    runs-on: ubuntu-latest
    environment: synapseqa
    steps:

      - name: Issue Forms Body Parser
        id: parse
        uses: zentered/issue-forms-body-parser@v1.2.1
        
      - run: |
          echo -e ${{ toJSON(steps.parse.outputs.data) }}

      - uses: 
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v3

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: synapseeus
          template: ./template/template.json
          parameters: name=mysynapse defaultDataLakeStorageAccountName=jmmysynapsestg defaultDataLakeStorageFilesystemName=jmmysynapsefs sqlServerPassword=${{ secrets.SQL_SERVER }}