# This is a basic workflow to help you get started with Actions

name: Create Infra

on:
  issues:
    types: [ opened, edited ]

jobs:      
  deploy:
    if: ${{ startsWith(github.event.issue.title, '[Create]') }}
    runs-on: ubuntu-latest
    environment: synapseqa
    steps:
      - uses: actions/checkout@v3

      - name: GitHub Issue Parser
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/create-synapse-environment.yml          
        
      - run: |
          echo ${{ steps.issue-parser.outputs.jsonString }}
          echo ${{ fromJSON(steps.issue-parser.outputs.jsonString) }}
          echo ${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }}
          exit 1          

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        id: template
        with:
          resourceGroupName: synapseeus
          template: ./template/template.json
          parameters: name=${{ steps.parse.outputs.data[0].text }} defaultDataLakeStorageAccountName=jmmysynapsestg defaultDataLakeStorageFilesystemName=jmmysynapsefs sqlAdministratorLoginPassword=${{ secrets.SQL_SERVER }}

  close-on-success:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ success() }}
    permissions:
      issues: write
    steps:
      - name: Close Issue after using its data
        uses: peter-evans/close-issue@v2
        with:
          comment: "@${{ github.event.issue.user.login }} this issue was automatically closed after creating the resource"

  comment-on-failure:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    permissions:
      issues: write
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            :warning: Run :  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.