name: Create Infra

on:
  issues:
    types: [ opened, edited ]

jobs:
  deploy:
    if: ${{ startsWith(github.event.issue.title, '[Create]') }}
    runs-on: ubuntu-latest
    outputs:
      demo-data: "$${{ fromJSON(steps.issue-parser.outputs.jsonString).demo-data }}"
    permissions:
      issues: write
    environment: synapseqa
    steps:
      - name: Create comment for start
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            **Starting deployment**
            Follow the run through this link:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} 

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: actions/checkout@v3

      - name: GitHub Issue Parser
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/create-synapse-environment.yml
          
      - name: Deploy Synapse ARM Template
        uses: Azure/arm-deploy@v1
        id: template
        with:
          resourceGroupName: ${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-group }}
          deploymentName: ghdeploy_${{ github.event.issue.number }}_${{ github.run_id }}
          template: ./template/template.bicep
          parameters: name=${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }} sqlAdministratorLoginPassword=${{ secrets.SQL_SERVER }} userObjectId=${{ secrets.OBJECTID }} 
          # userLoginName=${{ secrets.USER }}

      # This step is needed to get access to the user/group to the Synapse, if it is not assigned the workspace will show strange permission errors
      - name: Assign SQL Administrator to OBJECTID user
        run: az synapse role assignment create --workspace-name ${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }}  --role "Synapse SQL Administrator" --assignee ${{ secrets.OBJECTID }}      

      - name: Close Issue after creating Synapse Environment
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            **Deployment finished. Your workspace has been created**
            Link to your newly created workspace: ${{ steps.template.outputs.workspaceLink }}            
            @${{ github.event.issue.user.login }} this issue was automatically closed after creating the resource
            
            Run :  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} success.

  deploy-demo-data:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ needs.deploy.outputs.demo-data == 'Demo data' }}
    environment: synapseqa
    permissions:
      issues: write
    steps:
      - run: echo "upload data"

  comment-on-failure:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    permissions:
      issues: write
    steps:
      - name: Create failure comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            :warning: Run :  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.