name: Create Infra

on:
  issues:
    types: [ opened, edited ]

jobs:
  deploy:
    if: ${{ startsWith(github.event.issue.title, '[Create]') }}
    runs-on: ubuntu-latest
    outputs:
      demo-data: "${{ fromJSON(steps.issue-parser.outputs.jsonString).demo-data }}"
      storage-name: "${{ steps.template.outputs.storageName }}"
      container-name: "${{ steps.template.outputs.containerName }}"
      resource-name: "${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }}"
      resource-group: "${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-group }}"
    permissions:
      issues: write
    environment: synapseqa
    steps:
      - name: Create comment for start
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            **Starting deployment**
            Follow the run through this link:  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} 

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Current user objectId
        id: get-current-id
        run: |
          spName=$(az account show --query user.name -o tsv)
          echo "::set-output name=spsid::$(az ad sp show --id $spName --query objectId -o tsv)"

      - uses: actions/checkout@v3

      - name: GitHub Issue Parser
        uses: stefanbuck/github-issue-parser@v2
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/create-synapse-environment.yml
          
      - name: Deploy Synapse ARM Template
        uses: Azure/arm-deploy@v1
        id: template
        with:
          resourceGroupName: ${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-group }}
          deploymentName: ghdeploy_${{ github.event.issue.number }}_${{ github.run_id }}
          template: ./template/template.bicep
          parameters: name=${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }} sqlAdministratorLoginPassword=${{ secrets.SQL_SERVER }} userObjectId=${{ secrets.OBJECTID }} spSid=${{ steps.get-current-id.outputs.spsid }}
          # userLoginName=${{ secrets.USER }}

      # This step is needed to get access to the user/group to the Synapse, if it is not assigned the workspace will show strange permission errors
      - name: Assign SQL Administrator to OBJECTID user
        run: az synapse role assignment create --workspace-name ${{ fromJSON(steps.issue-parser.outputs.jsonString).resource-name }}  --role "Synapse SQL Administrator" --assignee ${{ secrets.OBJECTID }}      

      - name: Close Issue after creating Synapse Environment
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            **Deployment finished. Your workspace has been created**
            Link to your newly created workspace: ${{ steps.template.outputs.workspaceLink }}            
            @${{ github.event.issue.user.login }} this issue was automatically closed after creating the resource
            
            Run :  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} success.

  deploy-demo-data:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ needs.deploy.outputs.demo-data == 'Demo data' }}
    environment: synapseqa
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v3
      - run: |
          echo "upload data"
          az storage blob upload --account-name ${{ needs.deploy.outputs.storage-name }} --container-name "${{ needs.deploy.outputs.container-name }}" --name NYCTripSmall.parquet --file data/NYCTripSmall.parquet --auth-mode login
  workspace-deployment:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ needs.deploy.outputs.demo-data == 'Demo data' }}
    environment: synapseqa
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: ${{ needs.deploy.outputs.resource-name }}
          TemplateFile: './jmsynapsews/TemplateForWorkspace.json'
          ParametersFile: './jmsynapsews/TemplateParametersForWorkspace.json'
          OverrideArmParameters: './jmsynapsews/TemplateParametersForWorkspace.json'
          environment: 'Azure Public'
          resourceGroup: ${{ needs.deploy.outputs.resource-group }}
          clientId: ${{secrets.CLIENTID}}
          clientSecret:  ${{secrets.CLIENTSECRET}}
          subscriptionId: '${{secrets.SUBSCRIPTIONID}}'
          tenantId: '${{secrets.TENANTID}}'
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
  comment-on-failure:
    needs: [deploy, deploy-demo-data, workspace-deployment]
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    permissions:
      issues: write
    steps:
      - name: Create failure comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number:  ${{ github.event.issue.number }}
          body: |
            :warning: Run :  ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
            @${{ github.event.issue.user.login }} Check the logs for more information.